---
title: "Coding Session: Data Exploration"
author: "Environmental Data Analytics | Rachel Gonsenhauser"
date: "Spring 2020"
output: pdf_document
geometry: margin=2.54cm
---

##Setup 

```{r setup, include=FALSE}
# Setting up session
setwd("/Users/rachelgonsenhauser/Documents/Final_Project_Environmental_Data_Analytics")
getwd()
library(dplyr)
library(tidyverse)
library(lubridate)

# Pulling in processed dataset
Water.Quality.And.Income.Processed <- read.csv("../Data/Processed/CDC_WaterQualityAndincome_Processed.csv")

mytheme <- theme_classic() +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)
```

## Preliminary data exploration of processed dataset

```{r}
# Data exploration of processed dataset
colnames(Water.Quality.And.Income.Processed)
dim(Water.Quality.And.Income.Processed)
str(Water.Quality.And.Income.Processed)

class(Water.Quality.And.Income.Processed$Year)
class(Water.Quality.And.Income.Processed$State)
class(Water.Quality.And.Income.Processed$PWS.ID)
class(Water.Quality.And.Income.Processed$stateFIPS)
class(Water.Quality.And.Income.Processed$countyFIPS)
class(Water.Quality.And.Income.Processed$County)
class(Water.Quality.And.Income.Processed$PWS.ID)
class(Water.Quality.And.Income.Processed$CWS.Name)

#Changing population variable to numeric variable
class(Water.Quality.And.Income.Processed$Population.Served)
class(Water.Quality.And.Income.Processed$Population.Served) <- as.numeric(Water.Quality.And.Income.Processed$Population.Served)

class(Water.Quality.And.Income.Processed$MHI)
class(Water.Quality.And.Income.Processed$Arsenic_ugL)
class(Water.Quality.And.Income.Processed$PFAS_ppt)
class(Water.Quality.And.Income.Processed$TTHM_ugL)
class(Water.Quality.And.Income.Processed$Uranium_ugL)
class(Water.Quality.And.Income.Processed$MCL_Arsenic)
class(Water.Quality.And.Income.Processed$MCL_TTHM)
class(Water.Quality.And.Income.Processed$MCL_Uranium)

# Changing FIPs codes to factor variables 
class(Water.Quality.And.Income.Processed$countyFIPS)
Water.Quality.And.Income.Processed$countyFIPS <- as.factor(Water.Quality.And.Income.Processed$countyFIPS)
class(Water.Quality.And.Income.Processed$countyFIPS)

class(Water.Quality.And.Income.Processed$stateFIPS)
Water.Quality.And.Income.Processed$stateFIPS <- as.factor(Water.Quality.And.Income.Processed$stateFIPS)
class(Water.Quality.And.Income.Processed$stateFIPS)

# Changing contaminant and MHI variables to numeric variables
Water.Quality.And.Income.Processed$MHI <-
  str_replace(Water.Quality.And.Income.Processed$MHI,
              pattern = "([,])", replacement = "")
class(Water.Quality.And.Income.Processed$MHI)
Water.Quality.And.Income.Processed$MHI <- as.numeric(Water.Quality.And.Income.Processed$MHI)
class(Water.Quality.And.Income.Processed$MHI)

class(Water.Quality.And.Income.Processed$Arsenic_ugL)
Water.Quality.And.Income.Processed$Arsenic_ugL <- as.numeric(Water.Quality.And.Income.Processed$Arsenic_ugL)
class(Water.Quality.And.Income.Processed$Arsenic_ugL)

class(Water.Quality.And.Income.Processed$PFAS_ppt)
Water.Quality.And.Income.Processed$PFAS_ppt <- as.numeric(Water.Quality.And.Income.Processed$PFAS_ppt)
class(Water.Quality.And.Income.Processed$PFAS_ppt)

class(Water.Quality.And.Income.Processed$TTHM_ugL)
Water.Quality.And.Income.Processed$TTHM_ugL <- as.numeric(Water.Quality.And.Income.Processed$TTHM_ugL)
class(Water.Quality.And.Income.Processed$TTHM_ugL)

class(Water.Quality.And.Income.Processed$Uranium_ugL)
Water.Quality.And.Income.Processed$Uranium_ugL <- as.numeric(Water.Quality.And.Income.Processed$Uranium_ugL)
class(Water.Quality.And.Income.Processed$Uranium_ugL)
```


## Data exploration of variables in full dataset 

```{r}
# Exploring data distributions 
mean(Water.Quality.And.Income.Processed$Arsenic_ugL)
sd(Water.Quality.And.Income.Processed$Arsenic_ugL)
summary(Water.Quality.And.Income.Processed$Arsenic_ugL)

ggplot(Water.Quality.And.Income.Processed) +
  geom_histogram(aes(x = Arsenic_ugL))

# Arsenic levels seem high, check back to original data - this is correct, checked original data
mean(Water.Quality.And.Income.Processed$MHI)
sd(Water.Quality.And.Income.Processed$MHI)
summary(Water.Quality.And.Income.Processed$MHI)

summary(Water.Quality.And.Income.Processed$Arsenic_ugL)

# Looking at distribution of some continuous variables
 ggplot(Water.Quality.And.Income.Processed, aes(x = MHI)) +
  geom_histogram(binwidth = 10000) + 
  scale_x_continuous(limits = c(0, 100000))
 
 ggplot(Water.Quality.And.Income.Processed, aes(x = Arsenic_ugL)) +
   geom_histogram(binwidth = 100) +
   scale_x_continuous(limits = c(0,3000))

# Looking at distribution of some categorial variables
ggplot(Water.Quality.And.Income.Processed, aes(x = MCL_Arsenic)) +
  geom_bar()

ggplot(Water.Quality.And.Income.Processed, aes(x = MCL_Uranium)) +
  geom_bar()

ggplot(Water.Quality.And.Income.Processed, aes(x = MCL_TTHM)) +
  geom_bar()
# Lots of NAs for TTHM and Uranium MCLs

# Frequency polygons for multiple continuous variables
ggplot(Water.Quality.And.Income.Processed) +
  geom_freqpoly(aes(x = Arsenic_ugL), bins = 50, color = "pink") +
  geom_freqpoly(aes(x = Uranium_ugL), bins = 50, color = "royalblue") +
  geom_freqpoly(aes(x = PFAS_ppt), bins = 50,  lty = 2, color = "orange") +
    geom_freqpoly(aes(x = TTHM_ugL), bins = 50,  lty = 2, color = "green") +
  scale_x_continuous(limits = c(0, 10000)) +
   theme(legend.position = "top")

ggplot(Water.Quality.And.Income.Processed) +
  geom_freqpoly(aes(x = Uranium_ugL, color = State), bins = 50) +
  scale_x_continuous(limits = c(0, 10000)) +
  theme(legend.position = "top")

# Box plots 
ggplot(Water.Quality.And.Income.Processed) +
  geom_boxplot(aes(x = Year, y = Arsenic_ugL))

ggplot(Water.Quality.And.Income.Processed) +
  geom_boxplot(aes(x = Year, y = TTHM_ugL))

# Changing class of Year to factor variable
class(Water.Quality.And.Income.Processed$Year)
Water.Quality.And.Income.Processed$Year <- as.factor(Water.Quality.And.Income.Processed$Year)

# Violin plots
 ggplot(Water.Quality.And.Income.Processed) +
  geom_violin(aes(x = Year, y = Arsenic_ugL), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count")
 # Violin plots show similar distribution each year, median around the same place and some large value outliers every year, not much annual variation
 
  ggplot(Water.Quality.And.Income.Processed) +
  geom_violin(aes(x = Year, y = MHI), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count")
  #MHI seems to have a slight upward trend over time
```

## Massachusetts data exploration

```{r}
Massachusetts.data <- filter(Water.Quality.And.Income.Processed, State == "Massachusetts") 
  
  ggplot(Massachusetts.data) +
  geom_violin(aes(x = Year, y = Arsenic_ugL), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count")
 #Interested in looking at arsenic in Massachusetts since lots of arsenic hot spots from underlying geology, not much variation from year to year, 2003 looks interesting though
  
    ggplot(Massachusetts.data) +
  geom_violin(aes(x = MCL_Arsenic, y = Population.Served), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count")
  
 # Scatterplots (relationships between continuous variables)
ggplot(Massachusetts.data) +
  geom_point(aes(x = MHI, y = Arsenic_ugL))
             
ggplot(Massachusetts.data) +
  geom_point(aes(x = PFAS_ppt, y = Arsenic_ugL))
             
ggplot(Massachusetts.data) +
  geom_point(aes(x = TTHM_ugL, y = Arsenic_ugL)) 

ggplot(Massachusetts.data) +
  geom_point(aes(x = Arsenic_ugL, y = Uranium_ugL))

summary(Massachusetts.data$Arsenic_ugL)
```

```{r}
install.packages("viridis")
install.packages("RColorBrewer")
install.packages("colormap")
library(viridis)
library(RColorBrewer)
library(colormap)

Mass.arsenic.plot <-
  ggplot(Massachusetts.data, aes(x = Year, y = Arsenic_ugL)) +
    geom_hline(yintercept = 10, lty = 1) +
   geom_text(x = 2014, y = 50, label = "Maximum contaminant level", hjust = 1) +
 geom_point(aes(color = MCL_Arsenic))  +
   labs(x = expression(Year), y = expression(Arsenic ~ (mu*g / L)),
       color = "Maximum contaminant level", shape = "") + 
    scale_color_brewer(palette = "Paired") +
  theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Mass.arsenic.plot)
# How is it that all the "exceed MCL" values aren't at the top arsenic concentrations? Ask Kateri about this, she said this looks strange, just put in the MCL as a line rather than coloring by OR could show with color to show problem I had with this in exploratory part of report


# comparison of diff water contaminants over time in Massachusetts, do this for one southeastern state to for comparison
  Arsenic.compare.plot <-
  ggplot(Massachusetts.data, aes(x = Year, y = as.numeric(Arsenic_ugL))) +
  geom_point(alpha = 0.7, color = "purple") +
    geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Arsenic ~ (mu*g / L))) +
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(Arsenic.compare.plot)

 Uranium.compare.plot <-
  ggplot(Massachusetts.data, aes(x = Year, y = Uranium_ugL)) +
  geom_point(alpha = 0.7, color = "dark green") +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Uranium ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(Uranium.compare.plot)

 TTHM.compare.plot <-
  ggplot(Massachusetts.data, aes(x = Year, y = TTHM_ugL)) +
  geom_point(alpha = 0.7, color = "dodgerblue") +
    geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Trihalomethane ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(TTHM.compare.plot)

  library(cowplot)
plot_grid(Massachusetts.data, Arsenic.compare.plot, Uranium.compare.plot, TTHM.compare.plot, ncol = 2, align = 'h', rel_heights = c(1, 1))
```

## Northeast states data exploration

```{r}
Northeast.States.data <- 
  filter(Water.Quality.And.Income.Processed, State == "Massachusetts" | State == "Rhode Island" | State == "New York" | State == "Connecticut" | State == "Delaware" | State == "Maine" | State == "Vermont" | State == "New Hampshire" | State == "New Jersey" | State == "Pennsylvania") 

ggplot(Northeast.States.data) +
  geom_violin(aes(x = State, y = MHI), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count")
  
ggplot(Northeast.States.data) +
  geom_violin(aes(x = State, y = PFAS_ppt), 
              draw_quantiles = c(0.25, 0.5, 0.75),
              scale = "count") 
     
ggplot(Northeast.States.data) +
  geom_freqpoly(aes(x = Population.Served, color = State), bins = 50) +
  scale_x_continuous(limits = c(0, 10000)) +
  theme(legend.position = "top")

ggplot(Northeast.States.data) +
  geom_freqpoly(aes(x = Arsenic_ugL, color = State), bins = 50) +
  scale_x_continuous(limits = c(0, 10000)) +
  theme(legend.position = "right")

# Northeast states comparison of arsenic plot -- this won't run...come back!

Northeast.arsenic.plot <- ggplot(Northeast.States.data, aes(x = Year, y = Arsenic_ugL, fill = State)) +
  geom_point(shape = 21, size = 2, alpha = 0.8) + 
       scale_color_brewer(palette = "Paired") +
    labs(x = expression("Year"), y = expression(Arsenic ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Northeast.arsenic.plot)
```

## Southeast states data exploration

```{r}
Southeast.States.data <- 
  filter(Water.Quality.And.Income.Processed, State == "North Carolina" | State == "South Carolina" | State == "Florida" | State == "Georgia" | State == "Virginia" | State == "Alabama" | State == "Tennessee" | State == "West Virginia" | State == "Mississippi" | State == "Kentucky" | State == "Louisiana") 

Southeast.arsenic.plot <- ggplot(Southeast.States.data, aes(x = Year, y = Arsenic_ugL, fill = State)) +
  geom_point(shape = 21, size = 2, alpha = 0.8) +
       scale_color_brewer(palette = "Paired") +
    labs(x = expression("Year"), y = expression(Arsenic ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Southeast.arsenic.plot)
```
## North Carolina exploration 

```{r}

NC.data <- filter(Water.Quality.And.Income.Processed, State == "North Carolina") 
  
  Arsenic.compare.plot2 <-
  ggplot(NC.data, aes(x = Year, y = as.numeric(Arsenic_ugL))) +
  geom_point(alpha = 0.7, color = "purple") +
    geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Arsenic ~ (mu*g / L))) +
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(Arsenic.compare.plot2)

 Uranium.compare.plot2 <-
  ggplot(NC.data, aes(x = Year, y = Uranium_ugL)) +
  geom_point(alpha = 0.7, color = "dark green") +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Uranium ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(Uranium.compare.plot2)

 TTHM.compare.plot2 <-
  ggplot(NC.data, aes(x = Year, y = TTHM_ugL)) +
  geom_point(alpha = 0.7, color = "dodgerblue") +
    geom_smooth(method = "lm", se = FALSE, color = "black") +
   labs(x = expression("Year"), y = expression(Trihalomethane ~ (mu*g / L))) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10)) 
print(TTHM.compare.plot2)

plot_grid(NC.data, Arsenic.compare.plot2, Uranium.compare.plot2, TTHM.compare.plot2, ncol = 2, align = 'h', rel_heights = c(1, 1))
```


## PFAS data exploration

```{r}
# Filtering to 2013-2015 to explore PFAS data (data only collected over this period for PFAS)
#deciding to leave NAs in for whole dataset, no reason to drop them

PFAS.data <- filter(Water.Quality.And.Income.Processed, Year == "2014" | Year == "2013" | Year == "2015") %>%
  select(PFAS_ppt, Population.Served, Year, State, MHI, County, CWS.Name)


Southeast.PFAS.plot <- 
  ggplot(subset(PFAS.data, State == "North Carolina" | State == "South Carolina" | State == "Florida" | State == "Georgia" | State == "Virginia" | State == "Alabama" | State == "Tennessee" | State == "West Virginia" | State == "Mississippi" | State == "Kentucky" | State == "Louisiana"),
aes(x = MHI, y = PFAS_ppt, fill = State)) +
  geom_point(shape = 21, size = 2, alpha = 0.8) +
       scale_color_brewer(palette = "Paired") +
    labs(x = expression("Median household income ($ per year)"), y = expression("PFAS (ppt)")) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Southeast.PFAS.plot)

Northeast.PFAS.plot <- 
  ggplot(subset(PFAS.data, State == "Massachusetts" | State == "Rhode Island" | State == "New York" | State == "Connecticut" | State == "Delaware" | State == "Maine" | State == "Vermont" | State == "New Hampshire" | State == "New Jersey" | State == "Pennsylvania"),
aes(x = MHI, y = PFAS_ppt, fill = State)) +
  geom_point(shape = 21, size = 2, alpha = 0.8) +
       scale_color_brewer(palette = "Paired") +
    labs(x = expression("Median household income ($ per year)"), y = expression("PFAS (ppt)")) + 
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Northeast.PFAS.plot)
```