---
title: "Coding Session: Data Visualization and Analysis"
author: "Environmental Data Analytics | Rachel Gonsenhauser"
date: "Spring 2020"
output: pdf_document
geometry: margin=2.54cm
---

##Setup 

```{r setup, include=FALSE}
# Setting up session
getwd()
library(dplyr)
library(tidyverse)
library(lubridate)

# Pulling in processed dataset
Water.Quality.And.Income.Processed <- read.csv("../Data/Processed/CDC_WaterQualityAndincome_Processed.csv")

mytheme <- theme_classic() +
 theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)
```

## Southeast states

```{r}
Water.Quality.And.Income.Processed$Year <- as.character(Water.Quality.And.Income.Processed$Year) 
Water.Quality.And.Income.Processed$State <- as.character(Water.Quality.And.Income.Processed$State) 
Water.Quality.And.Income.Processed$Arsenic_ugL <- as.numeric(Water.Quality.And.Income.Processed$Arsenic_ugL) 

# Southeast data 
Southeast.States.data <- 
  filter(Water.Quality.And.Income.Processed, State == "North Carolina" | State == "South Carolina" | State == "Florida" | State == "Georgia" | State == "Virginia" | State == "Alabama" | State == "Tennessee" | State == "West Virginia" | State == "Mississippi" | State == "Kentucky" | State == "Louisiana") 

South.carolina.data <- Southeast.States.data %>%
  filter(State == "South Carolina")
summary(South.carolina.data$Arsenic_ugL)

# ANOVA
install.packages("nlme")
install.packages("piecewiseSEM")
library(nlme) 
library(agricolae)
library(piecewiseSEM)

Southeast.arsenic.anova <- 
  aov(data = Southeast.States.data, Arsenic_ugL ~ State * Year)
summary(Southeast.arsenic.anova)

#In southeastern states, arsenic concentration differs significantly from year to year over the period of 1999-2018 (two-way ANOVA with interaction effects, F,19=142.31, p<0.0001). Arsenic concentration also differs significantly from state to state (two-way ANOVA with interaction effects, F,5=3346.86, p<0.0001). Additionally, there is a significant interaction between year and state on arsenic concentration (two-way ANOVA with interaction effects, F,72=24.18, p<0.0001).

TukeyHSD(Southeast.arsenic.anova)
Southeast.arsenic.groupings <- HSD.test(Southeast.arsenic.anova, 
                         "State", group = TRUE)
Southeast.arsenic.groupings

#Post-hoc Tukey test exhibited that NC and SC were not significantly different but were significantly different from FL and LA, from KY, and from WV. Additionally, FL and LA were not significantly different but were significantly different from the rest w/r/t mean annual arsenic concentration.
```

```{r}
# MLR
class(Southeast.States.data$MHI) <- as.numeric(Southeast.States.data$MHI)

Southeast.arsenic.regression <- lm(data = Southeast.States.data, Arsenic_ugL ~ MHI + Population.Served + Uranium_ugL + TTHM_ugL)
summary(Southeast.arsenic.regression)

# Result: in southeast states, only trihalomethane concentrations significantly predict arsenic concentrationns, with higher TTHM correlated with lower arsenic for this specific model (MLR: F-statistic=10.24, p<0.0001, DF=4 and 558)

Southeast.Pop.regression <- lm(data = Southeast.States.data, Population.Served ~ Uranium_ugL + Arsenic_ugL + MHI + TTHM_ugL)
summary(Southeast.Pop.regression)

# Result: in southeast states, again only TTHM predicts size of the CWS signinficantly in this specific model, with increasing TTHM predicting increased size of the water system pop (MLR: F=2.618, DF=4 and 558, p-value=0.03431)

# Will always have issues of omitted variable bias, really small R2 (0.01138 here)

Southeast.MHI.regression <- lm(data = Southeast.States.data, MHI ~ Uranium_ugL + Arsenic_ugL + Population.Served)
summary(Southeast.MHI.regression)

#Result: in southeast states, uranium, arsenic, and size of CWS pop are all significant predictors of MHI. oddly enough, increasing uranium and arsenic correlate with increasing MHI....not surprisingly, increasing CWS pop served correlates with increased MHI (MLR: F-statistic=8.141, DF=3 and 1783, p<0.0001)

#consider doing aic tests here
```

```{r}
# Southeast plots
install.packages("viridis")
install.packages("RColorBrewer")
install.packages("colormap")
library(viridis)
library(RColorBrewer)
library(colormap)

summary(Southeast.States.data$Population.Served)

Southeast.arsenic.plot <- ggplot(Southeast.States.data, 
                 aes(x = Population.Served, y = Arsenic_ugL)) +
   geom_hline(yintercept = 10, lty = 1) +
   geom_text(x = 2000000, y = 150, label = "Maximum contaminant level", hjust = 1) +
  geom_point(aes(color = State)) +
  xlim(0, 2300000) +
     scale_color_brewer(palette = "Paired") +
   labs(x = expression("Population served"), y = expression(Arsenic ~ (mu*g / L)),
       color = "State", shape = "") + 
  #scale_y_continuous(labels = waiver()) +
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Southeast.arsenic.plot)
```

## Northeast states

```{r}
#Northeast data

Northeast.States.data <- 
  filter(Water.Quality.And.Income.Processed, State == "Massachusetts" | State == "Rhode Island" | State == "New York" | State == "Connecticut" | State == "Delaware" | State == "Maine" | State == "Vermont" | State == "New Hampshire" | State == "New Jersey" | State == "Pennsylvania") 

#ANOVA

Northeast.States.data$State <- as.factor(Northeast.States.data$State)
Northeast.States.data$Year <- as.factor(Northeast.States.data$Year)
Northeast.States.data$Arsenic_ugL <- as.numeric(Northeast.States.data$Arsenic_ugL)

Northeast.arsenic.anova <- 
  aov(data = Northeast.States.data, Arsenic_ugL ~ State * Year)
summary(Northeast.arsenic.anova)

#In northeast states, arsenic concentration differs signficantly between states (two-way ANOVA with interaction effects, F,8: 676.69, p<0.0001). Arsenic concentration also differs significantly from year to year from 1999-2018 (two-way ANOVA with interaction effects, F,19: 89.72, p<0.0001). Additionally, there is a significant interaction effect between state and year onn arsenic concentration (two-way ANOVA with interaction effects, F,147: 13.83, p<0.0001).


TukeyHSD(Northeast.arsenic.anova)
Northeast.arsenic.groupings <- HSD.test(Northeast.arsenic.anova, 
                         "State", group = TRUE)
Northeast.arsenic.groupings

#Post-hoc Tukey test exhibits differences between the following states (show on plot with a, b, c written out)

#might be hard to do plot across so many years and states...
#Arsenic_ugL groups
#New Hampshire    720.1171      a
#Massachusetts    699.9178      a
#Connecticut      488.6614      b
#Rhode Island     449.5769     bc
#Maine            411.6514      c
#Pennsylvania     304.9685      d
#New Jersey       259.9066      e
#New York         230.4317      f
#Vermont          202.3668      f
```

```{r}
#MLR 
Northeast.arsenic.regression <- lm(data = Northeast.States.data, Arsenic_ugL ~ MHI + Population.Served + Uranium_ugL + TTHM_ugL)
summary(Northeast.arsenic.regression)

#Result: in northeast states, population served, uranium, and TTHM all significant predictors of arsenic concentration. increasing uranium and TTHM correalte with increasing arsenic, while increasing pop served correlates with decreased arsenic values meainng smaller utilities face more serious issues of arsenic contamination in the northeast (MLR: F-statistic=12.1, DF=4 and 505, p-value<0.0001)

Northeast.Pop.regression <- lm(data = Northeast.States.data, Population.Served ~ Uranium_ugL + Arsenic_ugL + MHI + TTHM_ugL)
summary(Northeast.Pop.regression)

#Result: in northeast states, arsenic and TTHM are significant predictors of pop served by utility. increasing arsenic concentration correlates with decreasing size of CWS and surprisingly increasing TTHM correlates with larger CWS (MLR: F-statistic=19.23, DF=4 and 505, p<0.0001)

Northeast.MHI.regression <- lm(data = Northeast.States.data, MHI ~ Uranium_ugL + Arsenic_ugL + Population.Served)
summary(Northeast.MHI.regression)

#Result: in northeast states, uranium and arsenic significanntly predict MHI, again surprisingly are positively correlated (MLR: F-statistic=31.33, DF=3 and 3452, p<0.0001)
```


```{r}
#Northeast plots
summary(Northeast.States.data$Population.Served)

Northeast.arsenic.plot <- ggplot(Northeast.States.data, 
                 aes(x = Population.Served, y = Arsenic_ugL)) +
   geom_hline(yintercept = 10, lty = 1) +
   geom_text(x = 5e+06, y = 150, label = "Maximum contaminant level", hjust = 1) +
  geom_point(aes(color = State)) +
  xlim(0, 8271000) +
     scale_color_brewer(palette = "Paired") +
   labs(x = expression("Population served"), y = expression(Arsenic ~ (mu*g / L)),
       color = "State", shape = "") + 
  #scale_y_continuous(labels = waiver()) +
    theme(legend.position = "bottom",
       legend.text = element_text(size = 10), legend.title = element_text(size = 10))
print(Northeast.arsenic.plot)
```

## Massachusetts 

```{r}
# MLR for arsenic

Mass.arsenic.regression <- lm(data = subset(Water.Quality.And.Income.Processed, State == "Massachusetts"), Arsenic_ugL ~ MHI + Uranium_ugL + Population.Served)
summary(Mass.arsenic.regression)

```

```{r, echo=FALSE,error=FALSE, message=FALSE, warning=FALSE, fig.cap="Arsenic concentration in Massachusetts by size of community water system and county"}

# Preliminary plot
#not enough colors in palette for all counties, so change if i include by county
Mass.arsenic.plot <- ggplot(subset(Water.Quality.And.Income.Processed, State == "Massachusetts"), 
                 aes(x = Population.Served, y = Arsenic_ugL, color = County)) +
  geom_point() +
  xlim(0, 2550000) +
  scale_color_brewer(palette = "Paired") +
    theme(legend.position = "bottom",
       legend.text = element_text(size = 12), legend.title = element_text(size = 12))
print(Mass.arsenic.plot)

summary(Massachusetts.data$Population.Served)
```

```{r}
# MLR for pop served
Mass.pop.regression <- lm(data = subset(Water.Quality.And.Income.Processed, State == "Massachusetts"), Population.Served ~ MHI + Uranium_ugL + Arsenic_ugL)
summary(Mass.pop.regression)

#plot here? think about it
```

## North Carolina analysis

```{r}
Water.Quality.And.Income.Processed$Arsenic_ugL <- as.numeric(Water.Quality.And.Income.Processed$Arsenic_ugL)
Water.Quality.And.Income.Processed$MHI <- as.numeric(Water.Quality.And.Income.Processed$MHI)
Water.Quality.And.Income.Processed$Population.Served <- as.numeric(Water.Quality.And.Income.Processed$Population.Served)
Water.Quality.And.Income.Processed$Uranium_ugL <- as.numeric(Water.Quality.And.Income.Processed$Uranium_ugL)

NC.arsenic.regression <- lm(data = subset(Water.Quality.And.Income.Processed, State == "North Carolina"), Arsenic_ugL ~ MHI + Uranium_ugL + Population.Served)
summary(NC.arsenic.regression)

#Results: Arsenic concentration in NC is significantly predicted by uranium concentration, with higher uranium correlated with higher arsenic (multiple linear regression: F=50.4, DF=3 and 599, p<0.0001). Small R2 here (0.1976) meaning that could be lots of omitted variables that also explain variation in arsenic in NC and also that relationship might be better described by a non-linear relationship...
```

```{r, echo=FALSE,error=FALSE, message=FALSE, warning=FALSE, fig.cap="Arsenic concentration in North Carolina by size of community water system and county"}

# SHOW THIS PLOT IN FINAL

NC.arsenic.plot <- ggplot(subset(Water.Quality.And.Income.Processed, State == "North Carolina"), 
                 aes(x = Population.Served, y = Arsenic_ugL, color = MHI)) +
  geom_point() +
  xlim(0, 818005) +
  scale_color_continuous(type = "viridis") +
    labs(x = "Population served", y = expression(Arsenic ~ (mu*g / L)),
       color = "Median household income", shape = "") +
    theme(legend.position = "right",
       legend.text = element_text(size = 12), legend.title = element_text(size = 12))
print(NC.arsenic.plot)

summary(NC.data$Population.Served)

# Trying to make same plot for MAssachusetts

MA.arsenic.plot <- ggplot(subset(Water.Quality.And.Income.Processed, State == "Massachusetts"), 
                 aes(x = Population.Served, y = Arsenic_ugL, color = MHI)) +
  geom_point() +
  xlim(0, 818005) +
  scale_color_continuous(type = "viridis") +
    labs(x = "Population served", y = expression(Arsenic ~ (mu*g / L)),
       color = "Median household income", shape = "") +
    theme(legend.position = "right",
       legend.text = element_text(size = 12), legend.title = element_text(size = 12))
print(MA.arsenic.plot)

```

##PFAS MLR analysis

```{r}
PFAS.data <- filter(Water.Quality.And.Income.Processed, Year == "2014" | Year == "2013" | Year == "2015") %>%
  select(PFAS_ppt, Population.Served, Year, State, MHI, County, CWS.Name)

PFAS.data$PFAS_ppt <- as.numeric(PFAS.data$PFAS_ppt)
PFAS.data$MHI <- as.numeric(PFAS.data$MHI)
PFAS.data$Population.Served <- as.numeric(PFAS.data$Population.Served)

PFAS.regression <- lm(data = PFAS.data, PFAS_ppt ~ MHI + Population.Served)
summary(PFAS.regression)

#MHI and pop served by CWS are not significant predictors of PFAS for data collected (multiple linear regression: F=0.5696, DF=2 and 86, p=0.5679). Again tiny R2.

PFAS.plot <- ggplot(PFAS.data, aes(x = Population.Served, y = PFAS_ppt, color = MHI)) +
 geom_point() +
  xlim(0, 3e+06) +
  scale_color_continuous(type = "viridis") +
    labs(x = "Population served", y = expression("PFAS (ppt)"),
       color = "Median household income", shape = "") +
    theme(legend.position = "right",
       legend.text = element_text(size = 12), legend.title = element_text(size = 12))
print(PFAS.plot)

# Try ANOVA for PFAS?

PFAS.anova <- 
  aov(data = PFAS.data, PFAS_ppt ~ State)
summary(PFAS.anova)

#PFAS does not vary significantly across states (one-way ANOVA: F=0.619, DF=17, p=0.866). Huge issue of missing data here (25,938 observations deleted due to missingness) so can't perform a robust analysis here. 

TukeyHSD(PFAS.anova)
PFAS.groupings <- HSD.test(PFAS.anova, 
                         "State", group = TRUE)
PFAS.groupings
```

