---
title: "Coding Session: Data Wrangling 1"
author: "Environmental Data Analytics | Rachel Gonsenhauser"
date: "Spring 2020"
output: pdf_document
geometry: margin=2.54cm
---
## Setup

```{r setup, include=FALSE}
# Setting up session
setwd("/Users/rachelgonsenhauser/Documents/Final_Project_Environmental_Data_Analytics")
getwd()
library(dplyr)
library(tidyverse)
library(lubridate)

# Loading in raw datasets
Arsenic <- read.csv("../Data/Raw/Arsenic/data_113417.csv")
Income <- read.csv("../Data/Raw/MHI/data_122206.csv")
PFAS <- read.csv("../Data/Raw/PFAS/data_112028.csv")
Trihalomethane <- read.csv("../Data/Raw/Trihalomethane/data_122753.csv")
Uranium <- read.csv("../Data/Raw/Uranium/data_113718.csv")
```

## Changing column headings for clean dataset join later

```{r}
#Changing column headings
colnames(Arsenic)
head(Arsenic)
summary(Arsenic)
colnames(Arsenic)[6] <-c("Arsenic_ugL") 
colnames(Arsenic)[8] <-c("MCL_Arsenic")
colnames(Arsenic)

colnames(Income)
head(Income)
summary(Income)
colnames(Income)[6] <-c("MHI")

colnames(PFAS)
head(PFAS)
summary(PFAS)
colnames(PFAS)[6] <-c("PFAS_ppt")

colnames(Trihalomethane)
head(Trihalomethane)
summary(Trihalomethane)
colnames(Trihalomethane)[6] <-c("TTHM_ugL")
colnames(Trihalomethane)[8] <-c("MCL_TTHM")

colnames(Uranium)
head(Uranium)
summary(Uranium)
colnames(Uranium)[6] <-c("Uranium_ugL")
colnames(Uranium)[8] <-c("MCL_Uranium")
```
## Changing classes prior to joining datasets 

```{r}
# Changing classes of variables before joining
class(Arsenic$Year)
Arsenic$Year <- as.numeric(Arsenic$Year)

class(Income$Year)
Income$Year <- as.numeric(Income$Year)

class(PFAS$Year)
# Dates for PFAS given as a range of 2013-2015, so I am changing them all to 2014 so I can integrate into dataset for possible analysis
PFAS$Year <- ((2013+2015)/2)
class(PFAS$Year)

class(Trihalomethane$Year)
Trihalomethane$Year <- as.numeric(Trihalomethane$Year)

class(Uranium$Year)
Uranium$Year <-as.numeric(Uranium$Year)
```
## Joining and filtering data for processed dataset

``` {r}
# Joining datasets
Arsenic.Income <- left_join(Arsenic, Income)
Arsenic.Income.PFAS <- left_join(Arsenic.Income, PFAS)
Arsenic.Income.PFAS.Trihalomethane <- left_join(Arsenic.Income.PFAS, Trihalomethane)
Arsenic.Income.PFAS.Trihalomethane.Uranium <- left_join(Arsenic.Income.PFAS.Trihalomethane, Uranium)
```

```{r, message}
# Filtering dataset down to just necessary columns
Water.Quality.And.Income.Processed <- 
  Arsenic.Income.PFAS.Trihalomethane.Uranium %>%
  select(stateFIPS:Arsenic_ugL, PWS.ID:Population.Served, MHI, PFAS_ppt, TTHM_ugL, Uranium_ugL, MCL_TTHM, MCL_Uranium, MCL_Arsenic)
```


# Saving processed dataset for next session
```{r}
write.csv(Water.Quality.And.Income.Processed, row.names = FALSE, file = "./Data/Processed/CDC_WaterQualityAndIncome_Processed.csv")
```
